### ISSUE TITLE
Test probability distribution matches the expected probabilites

### ISSUE THREAD

**Issue by jiqicn** [covid19ABM/comma#13]
Follows are my observation, but can be more than these:
- Unexpected actions compared to baseline
- Unexpect n_contacts (negative values)

It's understandable that the hypotheses are arbitrarily set based on the LA's input, but this also suggests that the hypothesis parameters setup should be considered carefully.

**Comment by n400peanuts** [comment]
After a careful evaluation of this task, I think this is not a reasonable task. The reason for this is that the probability strictly depends on the matrices which are defined by the user. The process for calculating it is correct, but more than having a v. trivial test in which we compare expected vs obtained probabilities (which I don't think is a useful test as the calculation is very trivial) I don't think this brings us a bigger advantage

**Comment by jiqicn** [comment]
Let's close it for now but I may want to look back at it after we have a complete simulation. In that case, if we observe too many conflicts, I may think about either rejecting some baselines or revising the hypothesis.
