### ISSUE TITLE
add test within model class that checks the input

### ISSUE THREAD

**Issue by n400peanuts** [covid19ABM/comma#33]

**Comment by jiqicn** [comment]
Things to be tested: for each hypothesis file, if

- its column set is a superset of agents' (one-hot encoded) features.
- its value set of the action column is a superset of the action set given by param_model.json.
- values in cells are within the expected range (e.g. we may not want to have -1000 as a value there)

And things to be done in the source code: 
- Identify the desired chunk from the hypothesis matrices, and
- Take care of the row/column orders.
