### ISSUE TITLE
Initialize the Bayesian Network(s) given the selected features.

### ISSUE THREAD

**Issue by jiqicn** [covid19ABM/comma#39]

**Comment by jiqicn** [comment]
After discussing with the LA, we got agreed that "living with child" this feature should be left out.

**Comment by jiqicn** [comment]
Hypotheses given by the LA that may assume some dependencies between features
- Those who were unemployed as a result of the COVID-19 crisis had worse mental health outcomes than those who remained employed (D, B, A, CF | Em)
- Using lifelines data (!), researchers found that women experienced more depression during lockdowns, and men more anxiety. (D, B | G)
- Highly educated women experience more depression symptoms and disorders from the COVID-19 lockdown than highly educated men (D | G, Ed)
- For anxiety symptoms and disorders, middle-income women have significantly less anxiety symptoms and disorders than men in this category in all periods. (B | SES, G)
- Reduction in social network size was associated with increases in loneliness, and consequently in mental health symptoms. Some of this reduction in social network size was buffered by an increase in online interactions, especially by higher-educated young people. Younger individuals, those with medium level of education, and those economically better off displayed higher probabilities of increased non-physical interpersonal contact.  (D, B, Ad | Ed, A, SES)
- Low SES individuals were less likely to comply with measures and to see friends/family, but were also more likely to experience loneliness and depression as a result of lockdowns (and were also less likely to use digital replacement methods for socializing) (D | SES)
- Feelings of loneliness increased on average for all respondents and in particular for those who live alone or have a disadvantaged socioeconomic position (D | SES, Partner, Parent)

**Comment by jiqicn** [comment]
```mermaid
graph LR

Gender --> Age
Gender --> Employment
Gender --> Partner
Gender --> Depression
Gender --> Burnout

Age --> Education
Age --> Employment
Age --> Partner
Age --> Depression
Age --> Burnout
Age --> Addiction

Education --> Employment
Education --> Partner
Education --> Depression
Education --> Burnout
Education --> Addiction

Employment --> Depression
Employment --> Burnout
Employment --> Addiction
Employment --> Fatigue
Employment --> Partner

Partner --> Depression
Partner --> Partner-difficulties

Parent --> Single-Parent
Parent --> Depression

SES --> Finance-difficulties
SES --> Housing-difficulties
SES --> Depression
SES --> Burnout
SES --> Addiction

Job-type --> Employment
```

**Comment by n400peanuts** [comment]
Hi Ji, I think this makes sense more or less, though I am not sure of this interpretation:

Feelings of loneliness increased on average for all respondents and in particular for those who live alone or have a disadvantaged socioeconomic position (Depression | SES, Partner, Parent)

Specifically for the Parent variable -- not sure being a single parent means that you live alone or you come from a disadvantaged socioeconomic position...But in general I think it makes more sense to ask Kristina about this, she knows her data best.

**Comment by jiqicn** [comment]
Hi @n400peanuts, 

> Specifically for the Parent variable -- not sure being a single parent means that you live alone or you come from a disadvantaged socioeconomic position...But in general I think it makes more sense to ask Kristina about this, she knows her data best.

Agree and we will definitely ask Kristina about how she feels. And you're right, I just realize that `parenthood` may not add a lot to the assumption of living alone or not, so I will remove it.

> Also, I am not sure why you would draw the dependencies from the variables from her hypotheses

I found lockdown to be the premise of those hypotheses that can be about many things, and I've collected those that seem to indicate some correlations between individual features. Besides those hypotheses, I have no other information about the dataset that can be used for building the network, or we do? If you feel that the network should be built on some other information, I'm also quite okay with it and please let me know.

**Comment by jiqicn** [comment]
Hi @n400peanuts, since Kristina sent us a new cross-tab form that eliminates the number of features to 10, the network structure should also be updated accordingly. I will find a time and make a new network this week if time allows.

**Comment by n400peanuts** [comment]
@jiqicn sounds good. I was wondering: is it possible to have gender and age independent of each other? And both contributing to the next variable (e.g., education)? I am not sure if we should have age depending on gender or vice versa, but if the implementation in python then becomes too convoluted, I also understand and it is fine to keep it as it is.

**Comment by jiqicn** [comment]
@n400peanuts I agree that in general there's no need to have age and gender depend on each other, but I guess the idea here is to fit our model to Kristina's data as much as possible to make sure our sample dataset looks similar enough to that (please correct me if I'm wrong). Regarding writing a summarization of that work, I think you're right and let's do that after we finalize the network structure design.

**Comment by jiqicn** [comment]
Network structure that includes all variable associations given by independence tests, but have no direction decided.

```mermaid
graph TD
G[Gender] --- A
G --- P
G --- S[Self-rated health]
G --- CJ[Critical Job]

A[Age] --- E
A --- P
A --- C
A --- H
A --- S
A --- CJ

E[Education] --- P
E --- D
E --- C
E --- H
E --- S
E --- CJ

U[Umemployed] --- P
U --- C
U --- H
U --- S

P[Partner] --- D
P --- C
P --- H
P --- S

D[Depressed] --- S

C[Children] --- H

H[Housing/financial trouble] --- S
```

**Comment by Astrid-p** [comment]
@jiqicn This is the updated Bayesian model with added direction for each connection, I also have it reviewed by Kristina. There are a few notes that I want to highlight: 
- The linkages without arrows are those that should be removed from the previous version.   
- The link highlighted in red is the additional one
I also want to have some questions that I want to confer with you about: 
- You will notice some bi-directional links that were highlighted in yellow. I have checked out some articles that built the Bayesian model of bi-directional connections. But in your opinion, is it too complicated to put into consideration in terms of the used ABM packages? If it is not possible, they can be adjusted into one-directional links as well. 
- Is it possible to remove some linkage? I didn't grasp how the team developed the previous Bayesian version in the last meeting. I understand all the previous links were decided based on the actual data from Kristina (the data shows the correlation between age and gender), is it correct? It would be nice if you could give me a short explanation of the original methodology if you have time 😥 .

Kind regards, 
--Astrid--

![COMMA Bayesian network 15June](https://github.com/covid19ABM/comma/assets/66571144/f4b64b4b-ef79-4a73-8ca8-3d56c2e9e5b4)

**Comment by jiqicn** [comment]
Hi @Astrid-p, thanks for the updates! Regarding your questions:

> * You will notice some bi-directional links that were highlighted in yellow. I have checked out some articles that built the Bayesian model of bi-directional connections. But in your opinion, is it too complicated to put into consideration in terms of the used ABM packages? If it is not possible, they can be adjusted into one-directional links as well.

I have no idea tbh how bi-directional connections work in Bayesian models, and thus no clue what is the gain by adding that. Also, all Python packages I know for building such Bayesian models are based on the assumption that models follow the causal structure of DAGs, which never allows a bidirected edge. So I would suggest that we start with unidirectional models.

> * Is it possible to remove some linkage? I didn't grasp how the team developed the previous Bayesian version in the last meeting. I understand all the previous links were decided based on the actual data from Kristina (the data shows the correlation between age and gender), is it correct?

You can do pruning based on your knowledge, i.e. expert knowledge. And if the previous version you mean is [this](https://github.com/covid19ABM/comma/issues/39#issuecomment-1582494703), you are right, it's learned from the real data, more explicitly, the cross-tab results given by Kristina a couple of weeks ago. 

And this is how I did that: Kristina had the chi-square independence test on pairwise features done in cross-tabs. From there, with the p-value of a feature pair to be less than or equal to a threshold (0.05 in general), we can decide to reject the null hypothesis of that pair, i.e. to say they are dependent on each other. In this way, I can figure out all the dependencies and build the network.

**Comment by Astrid-p** [comment]
Hi @jiqicn , 

Thank you for the clarification! I had the same thought about the bi-directional links, but still wanted to double-check with you if my assumption is correct. In this case, this is the final update of the BN
![COMMA Bayesian network 19Jun](https://github.com/covid19ABM/comma/assets/66571144/176df30a-6e04-4f9f-bf35-fd3a670fee4b)

**Comment by n400peanuts** [comment]
@jiqicn Can we proceed in implementing this structure while @Astrid-p tries in parallel to learn the structure from the data?

**Comment by Astrid-p** [comment]
@jiqicn @n400peanuts, I notice that `bnlearn` package also provides a function to fit data on the customized structures. We can build our own structure through 'make_DAG' and fit the data and structure through `parameter_learning`. Is this what you are looking for to run this BN as well?

**Comment by jiqicn** [comment]
@n400peanuts, I think the idea is exactly like what @Astrid-p said above. I also thought about computing those CPDs by hand before realizing the existence of the `parameter_learning`function, but I guess we don't have to do that now.
