### ISSUE TITLE
literature relevant for the comma model

### ISSUE THREAD

**Issue by n400peanuts** [covid19ABM/comma#41]
Hi @kristinathompson , @Astrid-p  and @jiqicn,

I am trying to gather the literature relevant for the comma model. I would greatly appreciate it if you could add literature here as well by adding more comments below, this would make it simpler to share the same knowledge about the topic as we progress in the project.

The literature I am interested in at the moment, is about studies that used the language and tools of ABMs to conduct simulations of independent, individual-based processes of complex health behaviours (such as diseases progression, for example, or mental health as in our case) over a heterogenous population. Note though that these studies **must not include interactions among agents**, as this is the peculiarity of the comma model as well.

So far, I found the following studies:

- [Day, Xian and Brugh (2013)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0066812). An agent-based model to simulate the development and course of the diabetic retinopathy (DR).
- [Veloso (2013)](https://www.sciencedirect.com/science/article/pii/S2211034813000400) An agent-based model to simulate individual patient prognosis affected by multiple sclerosis. Based on patient characteristics at disease onset, the model provides individual 30 years disability prediction.
- [Subramanian, Bobashev and Morris (2009)](https://aacrjournals.org/cebp/article/18/7/1971/164115/Modeling-the-Cost-Effectiveness-of-Colorectal). This ABM model was built to simulate the incidence and mortality rates of CRC in the average-risk population. 

Review papers:
- [Badham et al., (2018)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6284360/) Overview of ABMs applied to health research
- [Weinstein et al., (2003)](https://www.sciencedirect.com/science/article/pii/S1098301510601283) Best practices to build models of health care
- [Nianogo et al., (2015)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4330820/) Review of ABMs applied to assess public health risk factors
- [Zaidi et al., (2001)](https://www.researchgate.net/profile/Asghar-Zaidi-2/publication/265280929_Dynamic_Microsimulation_Models_A_Review_and_Some_Lessons_for_SAGE/links/54982cf90cf2eeefc30f7c4c/Dynamic-Microsimulation-Models-A-Review-and-Some-Lessons-for-SAGE.pdf) Extensive review of microsimulation models

**Comment by kristinathompson** [comment]
Hi Eva,

Sure thing! We can have a look.

All the best,

Kristina

From: Eva Viviani ***@***.***>
Sent: 31 May 2023 11:52
To: covid19ABM/comma ***@***.***>
Cc: Thompson, Kristina ***@***.***>; Mention ***@***.***>
Subject: [covid19ABM/comma] literature relevant for the comma model (Issue #41)


Hi @kristinathompson<https://github.com/kristinathompson> , @Astrid-p<https://github.com/Astrid-p> and @jiqicn<https://github.com/jiqicn>,

I am trying to gather the literature relevant for the comma model. I would greatly appreciate it if you could add literature here as well by adding more comments below, this would make it simpler to share the same knowledge about the topic as we progress in the project.

The literature I am interested in at the moment, is about studies that used the language and tools of ABMs to conduct simulations of independent, individual-based processes of complex health behaviours (such as diseases progression, for example, or mental health as in our case) over a heterogenous population. Note though that these studies must not include interactions among agents, as this is the peculiarity of the comma model as well.

So far, I found the following studies:

  *   Day, Xian and Brugh (2013)<https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0066812>. An agent-based model to simulate the development and course of the diabetic retinopathy (DR).
  *   Veloso (2013)<https://www.sciencedirect.com/science/article/pii/S2211034813000400> An agent-based model to simulate individual patient prognosis affected by multiple sclerosis. Based on patient characteristics at disease onset, the model provides individual 30 years disability prediction.
  *   Subramanian, Bobashev and Morris (2009)<https://aacrjournals.org/cebp/article/18/7/1971/164115/Modeling-the-Cost-Effectiveness-of-Colorectal>. This ABM model was built to simulate the incidence and mortality rates of CRC in the average-risk population.

-

**Comment by Astrid-p** [comment]
Hi Eva, 

I have been looking for the literature that aligns with the studies you are interested in. Based on my understanding, it seems that the types of studies you require fall within the domain of agent-based microsimulation modeling. In technical terms, microsimulation models primarily focus on individual-level behavior without explicit agent interactions and are often utilized to analyze and forecast the impacts of multiple interventions or policies on individuals. However, as you mentioned, agent-based microsimulation modeling is relatively uncommon in research, as interaction and emergence are vital elements of ABM. I was only able to find a few relevant articles that I believe may be of interest:

1. Uncertainty Analysis of an Activity-Based Microsimulation Model for Singapore [(Petrik et al., 2020)](https://www.sciencedirect.com/science/article/abs/pii/S0167739X1830150X?casa_token=dbxVlTVO_1UAAAAA:e1ZAdeQcAUbaphI0NBstlCje5wlm3YC886mtn28V2FUoNpbHptb3e1kb8W3fWPb5eBsNXcaTY7P).
2. Designing a Large-Scale Public Transport Network Using Agent-Based Microsimulation [(Manser et al., 2020)](https://www.sciencedirect.com/science/article/abs/pii/S0965856420305668).
3. Combining Microsimulation and Agent-Based Model for Micro-level Population Dynamics" [(Won Bae et al., 2016)](https://www.sciencedirect.com/science/article/pii/S1877050916307359)
4. The Impact of Demographic Change in the Balance Between Formal and Informal Old-Age Care in Spain [(Spijker et al., 2022)](https://www.cambridge.org/core/journals/ageing-and-society/article/abs/impact-of-demographic-change-in-the-balance-between-formal-and-informal-oldage-care-in-spain-results-from-a-mixed-microsimulationagentbased-model/58747A063FFDD4D38593AAD2951B0B6B).

The last two articles do incorporate a limited-scale interaction between agents; however, as stated by the authors, the interaction is not trivial.

Additionally, I have found some methodological sources that might prove helpful:

1. Dynamic Microsimulation Models for Health Outcomes: A Review" by [(Rutter et al., 2011)](https://journals.sagepub.com/doi/pdf/10.1177/0272989X10369005?casa_token=QGYTjzstQ6IAAAAA:bCQi6W1mGCPK6fb36d8oFsVVdl8lZ45gX3d3GVp7qgyXHabG0x6tnAJmZUx_Hr5qPR0ZVV6c2aY)
2. A Review of Microsimulation and Hybrid Agent-Based Approaches [(Birkin and Wu, 2011)](https://link.springer.com/chapter/10.1007/978-90-481-8927-4_3#Sec5_3).

I hope you find these resources helpful for your studies and please let me know what do you think. If you have any further questions or need additional assistance, please let me know. 

Best regards,

Astrid

**Comment by n400peanuts** [comment]
@Astrid-p Thank you very much, this is very helpful. I am going to read all of this :)
I agree that our work would situate best into the microsimulation literature, your references seem very relevant!
