### ISSUE TITLE
Sampling function with the given weights learned from IPF as input

### ISSUE THREAD

**Issue by jiqicn** [covid19ABM/comma#51]
The weights (probability of feature value combinations) are learned from the R code generated by @n400peanuts.

**Comment by jiqicn** [comment]
And I guess we will also need to map the column names and values in `ipf_weights.csv` that file to the values appearing in the hypothesis matrices.

**Comment by n400peanuts** [comment]
Hi @jiqicn! thanks a lot for this. I am going to look it up now, can I make changes in this branch or do you prefer to open a PR?

**Comment by jiqicn** [comment]
HI @n400peanuts, sorry for the late reply, but feel free to do it either way. And we can discuss the points that are not clear to you in our meeting later.
