### ISSUE TITLE
(Optional) Implement the learning process of IPF in Python

### ISSUE THREAD

**Issue by jiqicn** [covid19ABM/comma#52]
The [ipfn](https://github.com/Dirguis/ipfn) package is a possible way of doing this.

**Comment by jiqicn** [comment]
Something related to the effects of the initial seed values on the results: https://stats.stackexchange.com/questions/216129/iterative-proportional-fitting-starting-values

**Comment by n400peanuts** [comment]
project has been handed over so further development is within the LA's judgment and abilities
